using System;
using System.ComponentModel.DataAnnotations;

namespace MoviesService.Models
{
    public class Movie
    {
        /// <summary>
        /// temporary movie id which comes from UI when creating a new movie object
        /// or updating in the first use
        /// </summary>
        public Guid TempMovieId { get; set; }

        /// <summary>
        /// MovieId which will be generated by MovieLibrary
        /// </summary>
        public int MovieId { get; set; }

        [StringLength(50), Required]
        public string Title { get; set; }

        public string[] Cast { get; set; }

        [StringLength(50), Required]
        public string Classification { get; set; }

        [StringLength(50), Required]
        public string Genre { get; set; }

        [Range(0, 10)]
        public int Rating { get; set; }

        public int ReleaseDate { get; set; }
    }
}