using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MoviesLibrary;
using MoviesService.Business.Enum;
using MoviesService.Models;

namespace MoviesService.Business.Repository
{
    /// <summary>
    /// The interface for ReadRepository class for mocking purposes
    /// </summary>
    public interface IReadRepository
    {
        /// <summary>
        /// Retrieves the list of movies
        /// </summary>
        /// <returns></returns>
        IEnumerable<Movie> GetAllMovies();

        /// <summary>
        /// Retrieves the list of movies as a result of a search
        /// </summary>
        /// <param name="textToSearch">the text to search for</param>
        /// <returns>the list of movies</returns>
        IEnumerable<Movie> SearchMovies(string textToSearch);

        /// <summary>
        /// Retrieves the list of movies sorted by a particular property
        /// </summary>
        /// <param name="sortedBy">the property to sort the list by</param>
        /// <returns></returns>
        IEnumerable<Movie> GetMoviesSortedBy(SortedByEnum sortedBy);

        /// <summary>
        /// Inserts a movie object into MovieLibrary Db
        /// </summary>
        /// <param name="movie">MovieData object to insert into Db</param>
        /// <returns>Movie Id generated by Movie Library</returns>
        void InsertMovie(Movie movie);

        /// <summary>
        /// Updates the movie in MovieLibrary Db
        /// </summary>
        /// <param name="movie">Movie object to be updated</param>
        void UpdateMovie(Movie movie);
    }
}
