using MoviesLibrary;

namespace MoviesService.Business.Repository
{
    /// <summary>
    /// The interface for WriteRepository class for mocking purposes
    /// </summary>
    public interface IWriteRepository
    {
        /// <summary>
        /// Inserts a movie object into MovieLibrary Db
        /// </summary>
        /// <param name="movie">MovieData object to insert into Db</param>
        /// <returns>Movie Id generated by Movie Library</returns>
        int InsertMovie(MovieData movie);

        /// <summary>
        /// Updates the movie in MovieLibrary Db
        /// </summary>
        /// <param name="movie">Movie object to be updated</param>
        void UpdateMovie(MovieData movie);
    }
}
