using System;
using System.Collections.Generic;
using System.Linq;
using MoviesLibrary;
using MoviesService.Business.Helpers;
using MoviesService.Models;

namespace MoviesService.Business.Repository
{
    /// <summary>
    /// Repository class for wrapping MovieDataSource which is the actual Db
    /// </summary>
    public class WriteRepository : IWriteRepository
    {
        /// <summary>
        /// Db instance
        /// </summary>
        public MovieDataSource MovieDataSource { get; set; }

        /// <summary>
        /// Constructor
        /// </summary>
        public WriteRepository()
        {
            MovieDataSource = new MovieDataSource();
        }

        /// <summary>
        /// Inserts a movie object into MovieLibrary Db
        /// </summary>
        /// <param name="movie">MovieData object to insert into Db</param>
        /// <returns>Movie Id generated by Movie Library</returns>
        public int InsertMovie(Movie movie)
        {
            return MovieDataSource.Create(movie.ToMovieData());
        }

        /// <summary>
        /// Updates the movie in MovieLibrary Db
        /// </summary>
        /// <param name="movie">Movie object to be updated</param>
        public void UpdateMovie(Movie movie)
        {
            MovieDataSource.Update(movie.ToMovieData());
        }
    }
}